### PR TITLE
VMRay: Feature - add IOC and VTI actions

### PR DESCRIPTION
**Pull request by jthom-vmray**
Please ensure your pull request (PR) adheres to the following guidelines:

- Please refer to our contributing documentation for any questions on submitting a pull request, link: [Contribution Guide](https://github.com/splunk-soar-connectors/.github/blob/main/.github/CONTRIBUTING.md)

#### Please check if your PR fulfills the following requirements:
- [x] Testing of all the changes has been performed (for bug fixes / features)
- [x] The readme.html has been reviewed and added / updated if needed (for bug fixes / features)
- [x] Use the following format for the PR description: `<App Name>: <PR Type> - <PR Description>`
- [x] Provide release notes as part of the PR submission which describe high level points about the changes for the upcoming GA release.
- [x] Verify all checks are passing.
- [x] Do NOT use the `next` branch of the forked repo. Create separate feature branch for raising the PR.
- [x] Do NOT submit updates to dependencies unless it fixes an issue.
#### Please check the type of change your PR introduces:
- [ ] New App
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Documentation
- [ ] Other (please describe): 

## Security Considerations (REQUIRED)
- [ ] If you are exposing any endpoints using a [REST handler](https://docs.splunk.com/Documentation/SOAR/current/DevelopApps/RESTHandlers), 
  please document them in the `readme.html`.
- [ ] If this is a new connector or you are adding new actions
    - [ ] Please document in the `readme.html` all methods (eg, OAuth) used to authenticate 
      with the service that the connector is integrating with.
    - [ ] If any actions are unable to run on SOAR Cloud, please document this in the `readme.html`.
- [ ] Are you introducing any new cryptography modules? If yes, please elaborate their purpose:
- [ ] Are you are accessing the file system? If yes, please verify that you are only accessing paths returned through 
the [Vault](https://docs.splunk.com/Documentation/SOARonprem/5.2.1/DevelopApps/AppDevAPIRef#Vault) API.
- [ ] Are you are marking code to be ignored by Semgrep with [`nosemgrep`](https://semgrep.dev/docs/ignoring-files-folders-code/#ignoring-code-through-nosemgrep)?
If yes, please provide justification in an additional comment next to the ignored code.

  

## Release Notes (REQUIRED)
For one of VMRay's products - FinalVerdict - the customers will not have access to reports from which actions like ‘detonate file’ get additional information. We added two new actions to compensate for the lost information: 'get iocs' and 'get vtis'.

## What is the current behavior? (OPTIONAL)
~~- Describe the current behavior that you are modifying.~~

## What is the new behavior? (OPTIONAL)
~~- Describe the behavior or changes that are being added by this PR.~~

## Other information (OPTIONAL)
~~- Any other information that is important to this PR such as screenshots of how the component looks before and after the change.~~

## Pay close attention to (OPTIONAL)
~~- Any specific code change or test case points which must be addressed/reviewed at the time of GA release.~~

## Screenshots (if relevant)

---
Thanks for contributing!

### CODE REVIEW

**Comment by dvora-crest** [comment]
Hi @jthom-vmray,
As per our standard, the min_phantom_version should be 5.5.0. Can you please test your app on 5.5.0 and update the min_phantom_version?
Also, it says permission denied when I'm trying to push the code. So, can you please provide the required permission?
CC: @nastorSplunk

**Comment by dvora-crest** [comment]
Hi @jthom-vmray 
As we have to do few standard development changes, could you provide the write access for the branch?
Also could you please test the app on 5.5.0 phantom version and update the min_phantom_version in json?
Thanks!

**Comment by jthom-vmray** [comment]
> Hi @jthom-vmray, As per our standard, the min_phantom_version should be 5.5.0. Can you please test your app on 5.5.0 and update the min_phantom_version? Also, it says permission denied when I'm trying to push the code. So, can you please provide the required permission? CC: @nastorSplunk

Hi @dvora-crest. Sorry for the late response, but I was on vacation. I just gave you write access to the forked repository. That is what you meant, right? I will test the app with version 5.5.0 today and report back once I'm done.

**Comment by jthom-vmray** [comment]
@dvora-crest I changed the `min_phantom_version` back 5.5.0. We tested the changes with Splunk SOAR 5.5.0 and 6.0.0.

**Comment by dvora-crest** [comment]
Thanks for the update @jthom-vmray

**Review by mmomin-crest — APPROVED** [review]

**Review by dhwanis-crest — APPROVED** [review]

**Review by splunk-jessica — APPROVED** [review]

**Review by ishans-crest — APPROVED** [review]

**Pull request merged**
